// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv74rqq4VMSdUQOXvxiSrITQydPa97wrg',
    appId: '1:35891210795:web:e1109308edb96abbfc986e',
    messagingSenderId: '35891210795',
    projectId: 'homey-app-13c3a',
    authDomain: 'homey-app-13c3a.firebaseapp.com',
    storageBucket: 'homey-app-13c3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3BejUmbyzThT8L76z9sNRifpW-aR799c',
    appId: '1:35891210795:android:66ff361dd1b4b7dffc986e',
    messagingSenderId: '35891210795',
    projectId: 'homey-app-13c3a',
    storageBucket: 'homey-app-13c3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz55jm5ytX6cuwmH8TSJKeH5d7FD2ug8A',
    appId: '1:35891210795:ios:c815e12862677dabfc986e',
    messagingSenderId: '35891210795',
    projectId: 'homey-app-13c3a',
    storageBucket: 'homey-app-13c3a.appspot.com',
    iosBundleId: 'com.example.homeyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz55jm5ytX6cuwmH8TSJKeH5d7FD2ug8A',
    appId: '1:35891210795:ios:aa79497740a8869bfc986e',
    messagingSenderId: '35891210795',
    projectId: 'homey-app-13c3a',
    storageBucket: 'homey-app-13c3a.appspot.com',
    iosBundleId: 'com.example.homeyApp.RunnerTests',
  );
}
